package lya;

/* Generated By:JavaCC: Do not edit this line. ProyectoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProyectoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int class_declaration = 5;
  /** RegularExpression Id. */
  int modifier = 6;
  /** RegularExpression Id. */
  int type_specifier = 7;
  /** RegularExpression Id. */
  int boolean_literal = 8;
  /** RegularExpression Id. */
  int if_declaration = 9;
  /** RegularExpression Id. */
  int corchetes_abren = 10;
  /** RegularExpression Id. */
  int corchetes_cierran = 11;
  /** RegularExpression Id. */
  int parentesis_abren = 12;
  /** RegularExpression Id. */
  int parentesis_cierran = 13;
  /** RegularExpression Id. */
  int puntoYComa = 14;
  /** RegularExpression Id. */
  int asignador = 15;
  /** RegularExpression Id. */
  int integer_literal = 16;
  /** RegularExpression Id. */
  int identifier = 17;
  /** RegularExpression Id. */
  int operador_relacional = 18;
  /** RegularExpression Id. */
  int operador_aritmetico = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"class\"",
    "<modifier>",
    "<type_specifier>",
    "<boolean_literal>",
    "\"if\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"=\"",
    "<integer_literal>",
    "<identifier>",
    "<operador_relacional>",
    "<operador_aritmetico>",
  };

}
